const express=require("express"),cors=require("cors"),Database=require("better-sqlite3"),path=require("path");
const app=express(),db=new Database(path.join(__dirname,"fayra.db"));
app.use(cors());app.use(express.json({limit:"2mb"}));
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,email TEXT UNIQUE,password TEXT,role TEXT);
CREATE TABLE IF NOT EXISTS stores(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,name TEXT,city TEXT,verified INTEGER DEFAULT 0,description TEXT DEFAULT '');
CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY AUTOINCREMENT,store_id INTEGER,name TEXT,price INTEGER,stock INTEGER,category TEXT,description TEXT,image TEXT DEFAULT '📦',active INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,total INTEGER,status TEXT,payment_method TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS order_items(id INTEGER PRIMARY KEY AUTOINCREMENT,order_id INTEGER,product_id INTEGER,qty INTEGER,price INTEGER);
CREATE TABLE IF NOT EXISTS wallets(user_id INTEGER PRIMARY KEY,balance INTEGER DEFAULT 0,pending INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS withdrawals(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,amount INTEGER,status TEXT DEFAULT 'PENDING',created_at TEXT DEFAULT CURRENT_TIMESTAMP);`);
if(!db.prepare("SELECT 1 FROM users LIMIT 1").get()){
 const u=db.prepare("INSERT INTO users(name,email,password,role) VALUES(?,?,?,?)");
 u.run("FAYRA Admin","admin@fayra.local","admin123","admin");
 const s=u.run("Demo Seller","seller@fayra.local","seller123","seller");
 db.prepare("INSERT INTO stores(user_id,name,city,verified,description) VALUES(?,?,?,?,?)").run(s.lastInsertRowid,"FAYRA Phone","Palopo",1,"Toko gadget demo");
 db.prepare("INSERT INTO wallets(user_id,balance,pending) VALUES(?,?,?)").run(s.lastInsertRowid,0,0);
 const st=db.prepare("SELECT id FROM stores WHERE user_id=?").get(s.lastInsertRowid);
 const p=db.prepare("INSERT INTO products(store_id,name,price,stock,category,description,image) VALUES(?,?,?,?,?,?,?)");
 p.run(st.id,"iPhone 13 128GB Like New",5500000,7,"HP","Unit like new","📱");
 p.run(st.id,"AirPods Pro 2",2150000,12,"Elektronik","Wireless earbuds","🎧");
}
function auth(req,res,next){const id=req.header("x-user-id"),u=id&&db.prepare("SELECT id,name,email,role FROM users WHERE id=?").get(id);if(!u)return res.status(401).json({error:"Login diperlukan"});req.user=u;next()}
function role(r){return (req,res,next)=>{auth(req,res,()=>req.user.role===r?next():res.status(403).json({error:"Akses ditolak"}))}}
app.get("/api/health",(q,s)=>s.json({ok:true,version:"V4"}));
app.post("/api/auth/register",(q,s)=>{let {name,email,password,role="buyer",store_name,city="Palopo"}=q.body||{};if(!name||!email||!password)return s.status(400).json({error:"Data wajib belum lengkap"});try{let r=db.prepare("INSERT INTO users(name,email,password,role) VALUES(?,?,?,?)").run(name,email,password,role==="seller"?"seller":"buyer");if(role==="seller"){db.prepare("INSERT INTO stores(user_id,name,city) VALUES(?,?,?)").run(r.lastInsertRowid,store_name||name,city);db.prepare("INSERT INTO wallets(user_id) VALUES(?)").run(r.lastInsertRowid)}s.json({id:r.lastInsertRowid,name,email,role})}catch(e){s.status(409).json({error:"Email sudah digunakan"})});
app.post("/api/auth/login",(q,s)=>{let u=db.prepare("SELECT id,name,email,role FROM users WHERE email=? AND password=?").get(q.body.email,q.body.password);if(!u)return s.status(401).json({error:"Email/password salah"});s.json(u)});
app.get("/api/store/me",auth,(q,s)=>{let st=db.prepare("SELECT * FROM stores WHERE user_id=?").get(q.user.id);if(!st)return s.status(404).json({error:"Toko belum ada"});s.json(st)});
app.patch("/api/store/me",auth,(q,s)=>{let {name,city,description}=q.body,st=db.prepare("SELECT * FROM stores WHERE user_id=?").get(q.user.id);if(!st)return s.status(404).json({error:"Toko belum ada"});db.prepare("UPDATE stores SET name=?,city=?,description=? WHERE id=?").run(name||st.name,city||st.city,description??st.description,st.id);s.json({ok:true})});
app.get("/api/products",(q,s)=>s.json(db.prepare("SELECT p.*,st.name store_name,st.city,st.verified FROM products p JOIN stores st ON st.id=p.store_id WHERE p.active=1 ORDER BY p.id DESC").all()));
app.get("/api/seller/products",role("seller"),(q,s)=>{let st=db.prepare("SELECT id FROM stores WHERE user_id=?").get(q.user.id);s.json(db.prepare("SELECT * FROM products WHERE store_id=? ORDER BY id DESC").all(st.id))});
app.post("/api/seller/products",role("seller"),(q,s)=>{let {name,price,stock,category="Umum",description="",image="📦"}=q.body,st=db.prepare("SELECT id FROM stores WHERE user_id=?").get(q.user.id);if(!name||!price)return s.status(400).json({error:"Nama dan harga wajib"});let r=db.prepare("INSERT INTO products(store_id,name,price,stock,category,description,image) VALUES(?,?,?,?,?,?,?)").run(st.id,name,+price,+stock,category,description,image);s.json({id:r.lastInsertRowid})});
app.put("/api/seller/products/:id",role("seller"),(q,s)=>{let st=db.prepare("SELECT id FROM stores WHERE user_id=?").get(q.user.id);let {name,price,stock,category,description,image}=q.body;let r=db.prepare("UPDATE products SET name=?,price=?,stock=?,category=?,description=?,image=? WHERE id=? AND store_id=?").run(name,price,stock,category,description,image,q.params.id,st.id);s.json({updated:r.changes>0})});
app.delete("/api/seller/products/:id",role("seller"),(q,s)=>{let st=db.prepare("SELECT id FROM stores WHERE user_id=?").get(q.user.id);db.prepare("UPDATE products SET active=0 WHERE id=? AND store_id=?").run(q.params.id,st.id);s.json({ok:true})});
app.get("/api/seller/orders",role("seller"),(q,s)=>{let st=db.prepare("SELECT id FROM stores WHERE user_id=?").get(q.user.id);s.json(db.prepare(`SELECT DISTINCT o.id,o.user_id,o.total,o.status,o.payment_method,o.created_at,u.name buyer FROM orders o JOIN order_items oi ON oi.order_id=o.id JOIN products p ON p.id=oi.product_id JOIN users u ON u.id=o.user_id WHERE p.store_id=? ORDER BY o.id DESC`).all(st.id))});
app.patch("/api/seller/orders/:id/status",role("seller"),(q,s)=>{let st=db.prepare("SELECT id FROM stores WHERE user_id=?").get(q.user.id);let ok=db.prepare(`SELECT 1 x FROM order_items oi JOIN products p ON p.id=oi.product_id WHERE oi.order_id=? AND p.store_id=?`).get(q.params.id,st.id);if(!ok)return s.status(404).json({error:"Order tidak ditemukan"});db.prepare("UPDATE orders SET status=? WHERE id=?").run(q.body.status,q.params.id);s.json({ok:true})});
app.get("/api/seller/wallet",role("seller"),(q,s)=>s.json(db.prepare("SELECT * FROM wallets WHERE user_id=?").get(q.user.id)));
app.post("/api/seller/withdrawals",role("seller"),(q,s)=>{let amount=+q.body.amount,w=db.prepare("SELECT * FROM wallets WHERE user_id=?").get(q.user.id);if(!amount||amount>w.balance)return s.status(400).json({error:"Saldo tidak cukup"});let r=db.prepare("INSERT INTO withdrawals(user_id,amount) VALUES(?,?)").run(q.user.id,amount);db.prepare("UPDATE wallets SET balance=balance-? WHERE user_id=?").run(amount,q.user.id);s.json({id:r.lastInsertRowid,status:"PENDING"})});
app.get("/api/orders",auth,(q,s)=>s.json(db.prepare("SELECT * FROM orders WHERE user_id=? ORDER BY id DESC").all(q.user.id)));
app.post("/api/orders",auth,(q,s)=>{let items=q.body.items||[],get=db.prepare("SELECT * FROM products WHERE id=?"),rows=[],total=0;if(!items.length)return s.status(400).json({error:"Keranjang kosong"});for(let x of items){let p=get.get(x.product_id);if(!p||p.stock<x.qty||!p.active)return s.status(400).json({error:"Produk/stok tidak tersedia"});total+=p.price*x.qty;rows.push({p,qty:x.qty})}let tx=db.transaction(()=>{let o=db.prepare("INSERT INTO orders(user_id,total,status,payment_method) VALUES(?,?,?,?)").run(q.user.id,total,"PENDING",q.body.payment_method||"COD");let oi=db.prepare("INSERT INTO order_items(order_id,product_id,qty,price) VALUES(?,?,?,?)"),up=db.prepare("UPDATE products SET stock=stock-? WHERE id=?");rows.forEach(r=>{oi.run(o.lastInsertRowid,r.p.id,r.qty,r.p.price);up.run(r.qty,r.p.id)});return o.lastInsertRowid});s.json({order_id:tx(),total})});
app.get("/api/admin/stats",role("admin"),(q,s)=>{let users=db.prepare("SELECT COUNT(*) c FROM users").get().c,sellers=db.prepare("SELECT COUNT(*) c FROM users WHERE role='seller'").get().c,products=db.prepare("SELECT COUNT(*) c FROM products WHERE active=1").get().c,orders=db.prepare("SELECT COUNT(*) c FROM orders").get().c,gmv=db.prepare("SELECT COALESCE(SUM(total),0) x FROM orders WHERE status!='CANCELLED'").get().x;s.json({users,sellers,products,orders,gmv,commission:Math.floor(gmv*.03)})});
app.use(express.static(path.join(__dirname,"..","frontend")));
app.listen(3000,()=>console.log("FAYRA V4 http://localhost:3000"));